### PR TITLE
Run an arbitrary command when the pledge becomes available.

### PR DESCRIPTION
**Pull request by jeanblanchard**
Examples included are open in browser (default, same as the current behavior) and send an email (which allows to run the script even if you have a life, and don't spend your life in front of a computer ;) ).

### CODE REVIEW

**Comment by p1r473** [comment]
This has been implemented ages ago in a fork here 
https://github.com/urahara-san/kickstarter-pledge-watch-and-manage

**Comment by timur-tabi** [comment]
I don't like this change because it adds two more python files, and I really want this to be just one file.

**Comment by p1r473** [comment]
The implementation I linked is just one file

**Comment by p1r473** [comment]
The implementation I linked is still just one file

**Comment by jeanblanchard** [comment]
@timur-tabi yes the idea was to introduce modularity by decoupling the watch part from the action, thus allowing to plug another action without having to touch the existing code. If you favor simplicity over modularity, I'm fine keeping this as a fork.

@p1r473 I fail to see how this is the same thing. Neither the modularity nor the email notification are in the repository you mention. It does have plenty of other additions, but really the only thing in common is the base repository.

**Comment by p1r473** [comment]
You give it a path to a bat file, and in that bat file you can do anything. I have mine set up to send an email with BLAT, tweet, that tweet triggers an IFTTT event, also I implemented TTS in my bat file and about 5 other things too... My bat file alerts me a billion ways

**Comment by jeanblanchard** [comment]
You're right it did have that feature, although it is not mentioned in the readme. But anyway I could not make that script work in the first place with the current kickstarter website, which is actually what lead me to consider the up-to-date original project, and contribute to it.

**Comment by timur-tabi** [comment]
Well, if you want me to merge it, you need to remove the other Python files and merge them into the main source file.

**Pull request closed without merging**
